spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: Mysql@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  boot:
    message: Hello, Department Service Spring Cloud Bus Demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
