# application.yml
# (opzionale) posizione alternativa se non localhost:8888


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  server:
    port: 8081
    servlet:
      context-path: "api/employees"
    
custom:
    message: "Hello, Employee Service Spring Cloud Bus Demo: remote employee-service.yml"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
