spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: Mysql@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8081
  
boot:
  message: "Hello, Employee Service Spring Cloud Bus Demo: remote employee-service-local.yml"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
